[package]
name = "sockmap"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1.40.0" , features = ["full"]}
clap = {version = "4.5.20" , features = ["derive"]}
aes-gcm = "0.10.3"
aes = "0.8.4"
rand = "0.8.5"
rsa = "0.9.6"
bincode = "1.3.3"
